export enum adminRoute {
  RT_CATEGORY = "category",
  MT_CATEGORY = "Kategoriyalar",
  RT_PRODUCTS = "products",
  MT_PRODUCTS = "Mahsulotlar",
  RT_ORDER = "order",
  MT_ORDER = "Buyurtmalar",
  RT_ADMINS = "admins",
  MT_ADMINS = "Adminlar",
  RT_SINGLE_ADMIN = "admin",
  MT_SINGLE_ADMIN = "Admin",
  RT_ADD_ADMIN = "add admin",
  MT_ADD_ADMIN = "Admin qo'shish",
  MT_SINGLE_PRODUCT = "Mahsulot",
  RT_SINGLE_PRODUCT = "single product",
  RT_ADD_PRODUCT = "add product",
  MT_ADD_PRODUCT = "Mahsulot qo'shish",
  RT_ADD_CATEGORY = "add category",
  MT_ADD_CATEGORY = "Kategoriya qo'shish",
}
